### ISSUE TITLE
Error when compiling LOS for Xiaomi Mi 10T Pro

### ISSUE THREAD

**Issue by tg-mw** [xiaomi-sm8250-devs/android_device_xiaomi_apollon#3]
Hello,

I am trying to compile LOS for the Xiaomi Mi 10T Pro using [this](https://wiki.lineageos.org/devices/apollon/build) guide. Unfortunately, I get errors during the process that seem to be related to SELinux:

```
FAILED: build out/target/product/apollon/obj/FAKE/vendor_hwservice_contexts_test_intermediates/vendor_hwservice_contexts_test
Outputs: out/target/product/apollon/obj/FAKE/vendor_hwservice_contexts_test_intermediates/vendor_hwservice_contexts_test
Error: exited with code: 1
Command: /bin/bash -c "(out/host/linux-x86/bin/checkfc  -e -l out/target/product/apollon/obj/ETC/sepolicy_intermediates/sepolicy out/target/product/apollon/vendor/etc/selinux/vendor_hwservice_contexts ) && (mkdir -p out/target/product/apollon/obj/FAKE/vendor_hwservice_contexts_test_intermediates/ ) && (touch out/target/product/apollon/obj/FAKE/vendor_hwservice_contexts_test_intermediates/vendor_hwservice_contexts_test )"
Output:
libsepol.context_from_record: type hal_vpp_hwservice is not defined
libsepol.context_from_record: could not create context structure
out/target/product/apollon/vendor/etc/selinux/vendor_hwservice_contexts:  line 101 has invalid context u:object_r:hal_vpp_hwservice:s0
/bin/bash: line 1: 375439 Segmentation fault      (core dumped) ( out/host/linux-x86/bin/checkfc -e -l out/target/product/apollon/obj/ETC/sepolicy_intermediates/sepolicy out/target/product/apollon/vendor/etc/selinux/vendor_hwservice_contexts )



FAILED: build out/target/product/apollon/obj/FAKE/sepolicy_tests_intermediates/sepolicy_tests
Outputs: out/target/product/apollon/obj/FAKE/sepolicy_tests_intermediates/sepolicy_tests
Error: exited with code: 1
Command: /bin/bash -c "(out/host/linux-x86/bin/sepolicy_tests -l out/host/linux-x86/lib64/libsepolwrap.so                -f out/target/product/apollon/system/etc/selinux/plat_file_contexts  -f out/target/product/apollon/vendor/etc/selinux/vendor_file_contexts  -f out/target/product/apollon/system_ext/etc/selinux/system_ext_file_contexts  -f out/target/product/apollon/product/etc/selinux/product_file_contexts  -p out/target/product/apollon/obj/ETC/sepolicy_intermediates/sepolicy ) && (touch out/target/product/apollon/obj/FAKE/sepolicy_tests_intermediates/sepolicy_tests )"
Output:
The following types on /data/ must be associated with the "core_data_file_type" attribute: fingerprint_data_file
```

I also tried it with the vendor files from the GitLab repository mentioned [here](https://github.com/xiaomi-sm8250-devs/android_vendor_xiaomi) and by extracting the corresponding vendor files from the latest official build [here](https://download.lineageos.org/apollon), with the same result. Additionally, I found [this commit](https://github.com/AOSPA/android_device_xiaomi_ginkgo/commit/a6a26d1eb779fc705fc95b7689bc07cfc81dee24), which seems to try to solve a similar problem.

Is this a Bug or am I doing something wrong? Thank you for your help in advance!

**Comment by przekichane** [comment]
Pick the commit you mentonied, after that either make a clean build (`rm -rf out/`) or run `make api-stubs-docs-non-updatable-update-current-api`

**Comment by tg-mw** [comment]
Thank you for your help! Applying the changes in the commit worked. After that, I encountered other errors which I fixed using [this](https://github.com/ejbtrd/device_xiaomi_apollo/commit/fc66dab37bc7e27f4386aa2b0e4ae7b92166043e) and [this](https://github.com/ejbtrd/device_xiaomi_apollo/commit/9bf567e843d141ad4576db35d0171c248f99c5b9) commit from your repository.

Do you know if this is the repository used to compile the official apollon LOS images (as it seems to be identical to [this](https://github.com/LineageOS/android_device_xiaomi_apollon) repo in the LOS repositories)? Or are the fixes for these selinux bugs simply not published yet?

**Comment by przekichane** [comment]
These issues with sepolicy are happening only during `make dist`. I am not sure, but i think this command isn't used in LineageOS CI, instead `make bacon` is used. If you don't use it already, I advise you to use this command to build.
