### ISSUE TITLE
Lineage-17.* sources?

### ISSUE THREAD

**Issue by manicpixiedreamboy** [xiaomi-sm8250-devs/android_device_xiaomi_apollon#5]
Hey, just question: found this old xda post about lineage17 on apollon [https://forum.xda-developers.com/t/rom-unofficial-10-0-0-apollopro-lineageos-17-1.4195963/?__cf_chl_jschl_tk__=r7.m9z7VK.L0ejR4qSXkKUyGhHFzdyg4q60xUlMmoyw-1639139248-0-gaNycGzNClE](https://forum.xda-developers.com/t/rom-unofficial-10-0-0-apollopro-lineageos-17-1.4195963/?__cf_chl_jschl_tk__=r7.m9z7VK.L0ejR4qSXkKUyGhHFzdyg4q60xUlMmoyw-1639139248-0-gaNycGzNClE)

Sources are said to be in the xiaomi-sm8250-devs group, so question: are there device and kernel sources for lineage-17.1?

**Comment by SebaUbuntu** [comment]
This org is a 1:1 mirror or LineageOS repos related to Xiaomi SM8250, also used to push WIP commits
We don't keep unofficial stuff
